class ArduinoConstants:
    MESSAGE_PREFIX_READY = '!READY!'
    MESSAGE_PREFIX_RESULT = 'Result:'
    MESSAGE_PREFIX_LOG = 'Log:'
    MESSAGE_PREFIX_MEASUREMENT = 'Measurement:'
    MESSAGE_PREFIX_CONFIG = 'Config:'
    MESSAGE_PREFIX_CAMERAS = 'Cameras:'
    MESSAGE_PREFIX_LIDAR_MAP = 'Map:'